# como persistir dados em um container passando a tag -v ou --amout e passado o caminho de onde eu quero o arquivo

docker run -it '-v /Documentos/alura-estudo/docker/persistencia-de-dados:/app' ubuntu bash

docker run -it --mount type=bind,source=/Documentos/alura-estudo/docker/persistencia-de-dados,target=/app ubuntu bash

